name: clang format check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  clang_format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  # v1, NOT v2 or v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: clang format check prepare
        run: |
          python -m pip install clang-format
          pwd
          git diff origin/master --name-only > git_diff.txt

      - name: clang format check run
        shell: python
        run: |
          import os
          import subprocess
          import sys

          print("Python {}.{}.{}".format(*sys.version_info))
          with open("git_diff.txt") as in_file:
            modified_files = sorted(in_file.read().splitlines())
          print("{} files were modified.".format(len(modified_files)))

          cpp_exts = tuple(".c .c++ .cc .cpp .cu .cuh .cxx .h .h++ .hh .hpp .hxx".split())
          cpp_files = [file for file in modified_files if file.lower().endswith(cpp_exts)]
          print(f"{len(cpp_files)} C++ files were modified.")
          if not cpp_files:
            sys.exit(0)

          result = subprocess.run(["clang-format", "-n", "--Werror"] + cpp_files, capture_output=True, text=True)
          print("clang format errors:")
          print(result.stderr)
          sys.exit(result.returncode)
