name: HiNPS CI Check

on: [push]

jobs:
  HiNPS-CI:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: PyTest with coverage check
      run: |
        pwd
        mkdir build
        echo "OVER"
