name: HiNPS CI Check

on: [push]

jobs:
  HiNPS-CI:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: PyTest with coverage check
      run: |
        pwd
        mkdir build
        echo "OVER"

    - name: Install Setuptools
      run: python -m pip install --upgrade setuptools; python -m pip install clang-tidy

    - name: clang tidy check
      shell: python
      run: |
        import os
        import subprocess
        import sys

        git diff origin/master --name-only > git_diff.txt
        print("Python {}.{}.{}".format(*sys.version_info))
        with open("git_diff.txt") as in_file:
          modified_files = sorted(in_file.read().splitlines())
        print("{} files were modified.".format(len(modified_files)))

        cpp_exts = tuple(".c .c++ .cc .cpp .cu .cuh .cxx .h .h++ .hh .hpp .hxx".split())
        cpp_files = [file for file in modified_files if file.lower().endswith(cpp_exts)]
        print(f"{len(cpp_files)} C++ files were modified.")
        if not cpp_files:
          sys.exit(0)

        build_dir = "build"  # 检查的目录名称

        if os.path.exists(build_dir) and os.path.isdir(build_dir):
            print(f"The '{build_dir}' directory exists.")
        else:
            print(f"The '{build_dir}' directory does not exist. Exiting with an error.")
            sys.exit(1)

        result = subprocess.run(["clang-tidy", "-p", "build", "--warnings-as-errors=*"] + cpp_files, capture_output=True, text=True)
        print("clang tidy errors:")
        print(result.stdout)
        print(result.stderr)
        sys.exit(result.returncode)
