name: HiNPS CI Check

on: [push]

jobs:
  HiNPS-CI:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Set up Python 3.8
      # uses: actions/setup-python@v4
      # with:
      #   python-version: 3.8
      run: |
        conda install python==3.8
    - name: Set up PyTorch MM
      run: |
        dpkg -l | grep libffi
        echo "MM #########################"
    - name: Set up MPI and mpi4py
      run: |
        conda install openmpi mpi4py
    - name: Install other dependencies and HiNPS
      run: |
        pip install pytest pytest-cov pytest-xdist pytest-mpi
        # networkx required by trimesh.repair
        pip install networkx
        python setup.py develop
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: PyTest with coverage check
      run: |
        pwd
        # mkdir build
        echo "OVER"
